---
title: "BR US Discount Sensitivity full score data performance Summary"
output:
  html_document: default
  html_notebook: default
---

Load the data to the environment

```{r}
require(ff)
require(ffbase)

gp_data_all <-read.table.ffdf(file="//10.8.8.51/lv0/Move to Box/Mithun/projects/7. DS_New Training/1. data/BR_full_data_base.txt",
                              header = TRUE,VERBOSE = TRUE,
                              sep='|',colClasses = c(rep("numeric",50)))

gp_data_all <- subset(gp_data_all,select=c('customer_key','Response' ))

BR_US_train_score <- read.table.ffdf(file="//10.8.8.51/lv0/Move to Box/Mithun/projects/7. DS_New Training/1. data/BR_US_DS_train_Score.txt",sep=",",header = T,VERBOSE = TRUE,
                                colClasses = c(rep("numeric",23)))

Score_data <- merge(gp_data_all,BR_US_train_score[,c(1,22,23)],by.x = "customer_key" ,by.y = "Customer_key")

```
Create the deciles based on ensemble score by mean and median
```{r}
require(dplyr)
# By Mean Score
Score_data <- Score_data[order( - Score_data$MeanScore),]
Score_data$Mean_Decile <- as.numeric(cut(1:nrow(Score_data),breaks=quantile(0:nrow(Score_data),probs=seq(0,1,by=0.1)), labels=1:10,right=T))

summary_by_mean <- Score_data %>% group_by(Mean_Decile) %>% summarise(Num_Cust=n(),Num_Resp=sum(Response)) %>% mutate(Resp_rate=Num_Resp/Num_Cust ,Per_Resp_Cap = cumsum(Num_Resp)/sum(Num_Resp) , Lift = cumsum(Num_Resp)/cumsum(Num_Cust))

Score_data <- Score_data[order( - Score_data$MedianScore),]
# By Median Score
Score_data$Median_Decile <- as.numeric(cut(1:nrow(Score_data),breaks=quantile(0:nrow(Score_data),probs=seq(0,1,by=0.1)), labels=1:10,right=T))

summary_by_median <- Score_data %>% group_by(Median_Decile) %>% summarise(Num_Cust=n(),Num_Resp=sum(Response)) %>% mutate(Resp_rate=Num_Resp/Num_Cust ,Per_Resp_Cap = cumsum(Num_Resp)/sum(Num_Resp) , Lift = cumsum(Num_Resp)/cumsum(Num_Cust))

require(pROC)
require(AUC)
```

AUC curve by median score
```{r}
roc_median_score <- roc(Score_data$MedianScore,as.factor(Score_data$Response))
plot(roc_median_score, main="AUC curve by median score")
```

AUC curve by mean score
```{r}
roc_mean_score <- roc(Score_data$MeanScore,as.factor(Score_data$Response))
plot(roc_mean_score, main="AUC curve by mean score")

```

Overall AUC Value by mean score and median score


```{r}

auc(roc_mean_score) #0.7977377
auc(roc_median_score) #0.7977077

rm(roc_mean_score,roc_median_score)
gc()
```

Data summary by percentile 
```{r}

require(dplyr)
# By Mean Score
Score_data <- Score_data[order( - Score_data$MeanScore),]
Score_data$Mean_Percentile <- as.numeric(cut(1:nrow(Score_data),breaks=quantile(0:nrow(Score_data),probs=seq(0,1,by=0.01)), labels=1:100,right=T))

summary_by_mean_percentile <- Score_data %>% group_by(Mean_Percentile) %>% summarise(Num_Cust=n(),Num_Resp=sum(Response)) %>% mutate(Resp_rate=Num_Resp/Num_Cust ,Per_Resp_Cap = cumsum(Num_Resp)/sum(Num_Resp) , Lift = cumsum(Num_Resp)/cumsum(Num_Cust))

summary_by_mean_percentile$baseline_gain <- seq(0.01,1,by =0.01)
summary_by_mean_percentile$gain_over_bau <- summary_by_mean_percentile$Lift/(sum(summary_by_mean_percentile$Num_Resp)/sum(summary_by_mean_percentile$Num_Cust))


Score_data <- Score_data[order( - Score_data$MedianScore),]
# By Median Score
Score_data$Median_Percentile <- as.numeric(cut(1:nrow(Score_data),breaks=quantile(0:nrow(Score_data),probs=seq(0,1,by=0.01)), labels=1:100,right=T))

summary_by_median_percentile <- Score_data %>% group_by(Median_Percentile) %>% summarise(Num_Cust=n(),Num_Resp=sum(Response)) %>% mutate(Resp_rate=Num_Resp/Num_Cust ,Per_Resp_Cap = cumsum(Num_Resp)/sum(Num_Resp) , Lift = cumsum(Num_Resp)/cumsum(Num_Cust))
summary_by_median_percentile$baseline_gain <- seq(0.01,1,by =0.01)
summary_by_median_percentile$gain_over_bau <- summary_by_median_percentile$Lift / 0.1634871

#Baseline response rate 
#sum(summary_by_mean_percentile$Num_Resp)/sum(summary_by_mean_percentile$Num_Cust) #0.1634871

```
Cumulative Gain Chart
```{r}
require(ggplot2)

# Cumulative Gain Chart
ggplot(data=summary_by_mean_percentile,mapping = aes(x=Mean_Percentile))+geom_line(aes(y=baseline_gain, color="baseline_gain")) + 
  geom_line(aes(y=Per_Resp_Cap, color="Per_Resp_Cap")) + ylab("% Response Captured") + xlab("% Customer Contacted") +ggtitle("Cumulative Gain Chart by mean ensemble")
ggplot(data=summary_by_median_percentile,mapping = aes(x=Median_Percentile))+geom_line(aes(y=baseline_gain, color="baseline_gain")) + 
  geom_line(aes(y=Per_Resp_Cap, color="Per_Resp_Cap")) + ylab("% Response Captured") + xlab("% Customer Contacted") +ggtitle("Cumulative Gain Chart by median ensemble")

```
Base Response rate Chart
```{r}
#Base Response rate Chart
ggplot(data=summary_by_mean_percentile,mapping = aes(x=Mean_Percentile)) + geom_line(aes(y=Lift,color="Lift")) +geom_line(aes(y=0.1634871)) +
    ylab("% Response Rate to be Achieved") + xlab("% customers contacted") + ggtitle("Overall response rate by rank ordering by mean ensemble")
ggplot(data=summary_by_median_percentile,mapping = aes(x=Median_Percentile)) + geom_line(aes(y=Lift,color="Lift")) +geom_line(aes(y=0.1634871)) +
  ylab("% Response Rate to be Achieved") + xlab("% customers contacted") + ggtitle("Overall response rate by rank ordering by median ensemble")
```
Cumulative Lift Chart
```{r}

# Cumulative Lift Chart
ggplot(data=summary_by_mean_percentile,mapping = aes(x=Mean_Percentile)) + geom_line(aes(y=gain_over_bau,color="Lift")) +geom_line(aes(y=1, color="bau rate")) +
  ylab("Gain achieved over bau rate") + xlab("% customers contacted") + ggtitle("Cumulative Gain chart by mean ensemble")
ggplot(data=summary_by_median_percentile,mapping = aes(x=Median_Percentile)) + geom_line(aes(y=gain_over_bau,color="Lift")) +geom_line(aes(y=1, color="bau rate")) +
  ylab("Gain achieved over bau rate") + xlab("% customers contacted") + ggtitle("Cumulative Gain chart by median ensemble")

```

.
